# Generated by Django 6.0.6 on 2026-08-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='mensajeria/adjuntos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('imagen', 'Imagen'), ('audio', 'Audio')], default='texto', max_length=10),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='contenido',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
