# Generated by Django 6.0.6 on 2026-07-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('cita', 'Cita'), ('subasta', 'Subasta'), ('mensaje', 'Mensaje'), ('sistema', 'Sistema')], default='sistema', max_length=20),
        ),
    ]
