# Generated by Django 6.0.6 on 2026-07-13 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSwitches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switches', models.JSONField(blank=True, default=dict)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_switches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'configuración de switches',
                'verbose_name_plural': 'configuraciones de switches',
            },
        ),
    ]
