# Generated by Django 6.0.6 on 2026-07-01 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0005_departamento_municipio'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_ofrecidos', to='profesionales.perfilprofesional')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesionales_que_ofrecen', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'servicio ofrecido por profesional',
                'verbose_name_plural': 'servicios ofrecidos por profesionales',
                'ordering': ['precio'],
                'constraints': [models.UniqueConstraint(fields=('profesional', 'servicio'), name='servicio_unico_por_profesional')],
            },
        ),
    ]
