# Generated by Django 6.0.6 on 2026-07-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_servicioprofesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
