# Generated by Django 6.0.6 on 2026-07-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_servicio_duracion_minutos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='duracion_minutos',
        ),
        migrations.AddField(
            model_name='servicioprofesional',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
