# Generated by Django 6.0.6 on 2026-07-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_membresia_pago_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes_pago/'),
        ),
        migrations.AddField(
            model_name='pago',
            name='correo_pagador',
            field=models.EmailField(default=1, help_text='Correo desde el que se reportó/hizo la transferencia, para verificar quién pagó.', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='medio_pago',
            field=models.CharField(choices=[('nequi', 'Nequi'), ('llave', 'Llave')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='pasarela',
            field=models.CharField(default='manual', max_length=20),
        ),
    ]
