# Generated by Django 6.0.6 on 2026-07-27 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dias_prueba',
            field=models.PositiveIntegerField(default=15, help_text='Días de prueba gratuita permitidos para usuarios profesionales.'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='en_produccion',
            field=models.BooleanField(default=False, help_text='Si es False, la cuenta está en periodo de prueba (trial gratuito).'),
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('activa', 'Activa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membresia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
