# Generated by Django 6.0.6 on 2026-07-28 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_dias_prueba_usuario_en_produccion_membresia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membresia',
        ),
    ]
