# Generated by Django 6.0.6 on 2026-07-03 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('servicios', '0004_remove_servicio_duracion_minutos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='servicios.categoriaservicio'),
        ),
        migrations.AddField(
            model_name='cita',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cita',
            name='modo',
            field=models.CharField(default='profesional', max_length=20),
        ),
    ]
