# Generated by Django 6.0.6 on 2026-07-04 03:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_cita_categoria_cita_etiqueta_cita_modo'),
        ('profesionales', '0005_departamento_municipio'),
        ('servicios', '0004_remove_servicio_duracion_minutos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'cancelada'), _negated=True), fields=('profesional', 'fecha', 'hora_inicio'), name='unico_horario_profesional_activo'),
        ),
    ]
