# Generated by Django 6.0.6 on 2026-07-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_cita_unico_horario_profesional_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='iniciado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
