# Generated by Django 6.0.6 on 2026-07-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_admin', '0002_adminoperador_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminoperador',
            name='otp_secret',
        ),
        migrations.AddField(
            model_name='adminoperador',
            name='codigo_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='adminoperador',
            name='codigo_otp_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
