# Generated by Django 6.0.6 on 2026-06-26 17:28

import django.db.models.deletion
from django.db import migrations, models


def crear_estados_iniciales(apps, schema_editor):
    EstadoAtencion = apps.get_model('profesionales', 'EstadoAtencion')
    PerfilProfesional = apps.get_model('profesionales', 'PerfilProfesional')

    estados = [
        ('disponible', 'Disponible'),
        ('no_disponible', 'No disponible'),
        ('en_almuerzo', 'En almuerzo'),
        ('en_break', 'En break'),
    ]

    for codigo, nombre in estados:
        EstadoAtencion.objects.get_or_create(
            codigo=codigo,
            defaults={'nombre': nombre, 'activo': True},
        )

    estado_disponible = EstadoAtencion.objects.get(codigo='disponible')
    PerfilProfesional.objects.filter(estado__isnull=True).update(
        estado=estado_disponible,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0002_perfilprofesional_latitud_perfilprofesional_longitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'estado de atencion',
                'verbose_name_plural': 'estados de atencion',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='perfilprofesional',
            name='horarios_atencion',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='perfilprofesional',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profesionales', to='profesionales.estadoatencion'),
        ),
        migrations.RunPython(crear_estados_iniciales, migrations.RunPython.noop),
    ]
