from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0003_perfilprofesional_estado_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS profesionales_estadoatencion (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                codigo varchar(50) NOT NULL UNIQUE,
                nombre varchar(100) NOT NULL UNIQUE,
                activo boolean NOT NULL DEFAULT true,
                fecha_creacion timestamp with time zone NOT NULL DEFAULT now()
            );

            INSERT INTO profesionales_estadoatencion (codigo, nombre, activo, fecha_creacion)
            VALUES
                ('disponible', 'Disponible', true, now()),
                ('no_disponible', 'No disponible', true, now()),
                ('en_almuerzo', 'En almuerzo', true, now()),
                ('en_break', 'En break', true, now())
            ON CONFLICT (codigo) DO NOTHING;

            ALTER TABLE profesionales_perfilprofesional
            ADD COLUMN IF NOT EXISTS estado_id bigint;

            UPDATE profesionales_perfilprofesional perfil
            SET estado_id = estado.id
            FROM profesionales_estadoatencion estado
            WHERE perfil.estado_id IS NULL
            AND estado.codigo = 'disponible';

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'profesionales_perfilprofesional_estado_id_fkey'
                ) THEN
                    ALTER TABLE profesionales_perfilprofesional
                    ADD CONSTRAINT profesionales_perfilprofesional_estado_id_fkey
                    FOREIGN KEY (estado_id)
                    REFERENCES profesionales_estadoatencion(id)
                    DEFERRABLE INITIALLY DEFERRED;
                END IF;
            END $$;

            CREATE INDEX IF NOT EXISTS profesionales_perfilprofesional_estado_id_idx
            ON profesionales_perfilprofesional (estado_id);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
