# Generated by Django 6.0.6 on 2026-07-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0005_departamento_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprofesional',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profesionales/perfiles/%Y/%m/'),
        ),
    ]
