# Generated by Django 6.0.6 on 2026-07-11 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0007_eliminar_columna_estado_obsoleta'),
        ('profesionales', '0008_enable_pg_extensions'),
    ]

    operations = [
    ]
