# Generated by Django 6.0.6 on 2026-07-12 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_cita_unico_horario_profesional_activo'),
        ('profesionales', '0010_calificacionprofesional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPortafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='profesionales/portafolio/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_portafolio', to='citas.cita')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_de_mis_servicios', to=settings.AUTH_USER_MODEL)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portafolio', to='profesionales.perfilprofesional')),
            ],
            options={
                'verbose_name': 'imagen de portafolio',
                'verbose_name_plural': 'imágenes de portafolio',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
