# Generated by Django 6.0.6 on 2026-07-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0011_imagenportafolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprofesional',
            name='notificar_citas_por_correo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilprofesional',
            name='notificar_mensajes_por_correo',
            field=models.BooleanField(default=True),
        ),
    ]
